- hosts: localhost
  collections:
    - community.general
  pre_tasks:
  - name: Update Pacman
    become: true
    community.general.pacman:
      update_cache: true
      upgrade: true
    tags:
      - core
  - name: Play needed tasks in order
    include_tasks: "{{ item }}"
    loop:
      - tasks/git.playbook.yaml
      - tasks/shell.playbook.yaml
      - tasks/cool.playbook.yaml
      - tasks/editor.playbook.yaml
      - tasks/code.playbook.yaml
      - tasks/brave.playbook.yaml
