- hosts: localhost
  collections:
    - community.general
  tasks:
  - name: Install Zsh
    community.general.pacman:
      name: zsh
      state: present
    become: true

  - name: Check if Oh My Zsh is already installed
    stat:
      path: "{{ ansible_env.HOME }}/.oh-my-zsh"
    register: oh_my_zsh

  - name: Install Oh My Zsh for the current user
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    args:
      creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
    when: not oh_my_zsh.stat.exists

  - name: Change the default shell to Zsh
    user:
      name: "{{ ansible_user_id }}"
      shell: /bin/zsh
    become: true
    when: not oh_my_zsh.stat.exists

  - name: Install zsh-autosuggestions plugin
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      depth: 1
    when: not oh_my_zsh.stat.exists

  - name: Update .zshrc to include zsh-autosuggestions plugin
    lineinfile:
      path: "{{ ansible_env.HOME }}/.zshrc"
      regexp: '^(plugins=\()'
      line: 'plugins=(git zsh-autosuggestions)'
      backrefs: yes
    when: not oh_my_zsh.stat.exists
